name: deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - deploy

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hooks
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: ${{secrets.HOOKS_URL}}
          method: "POST"
